minVersion: 0.23.1
changelogPolicy: none
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: github
  - name: registry
    sdks:
      npm:platformicons:
        includeNames: /none/