name: Publish to npm
on:
    push:
        tags:
            - "*"

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm ci

            - name: Publish to npm
              env:
                  NPM_TOKEN: ${{ secrets.NPM_ACCESS_KEY }}
              run: npm publish
